doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        server_version: '12.2'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8mb4_unicode_ci

        types:
            game_id: 'App\Domain\Store\Entity\Game\IdType'
            game_price: 'App\Domain\Store\Entity\Game\PriceType'
            game_status: 'App\Domain\Store\Entity\Game\StatusType'

            auth_user_id: 'App\Infrastructure\User\Types\IdType'
            auth_user_email: 'App\Infrastructure\User\Types\EmailType'
            auth_user_role: 'App\Infrastructure\User\Types\RoleType'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Auth:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Auth/Entity'
                prefix: 'App\Domain\Auth\Entity'
                alias: Auth
            Store:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Store/Entity'
                prefix: 'App\Domain\Store\Entity'
                alias: Parser
